import fs from "fs";
import path from "path";
import { writeCapabilities } from "ai-jue-core";
import type {
  ArtifactChange,
  CanonicalDocument,
  WriteContext as CoreWriteContext,
} from "ai-jue-core";
import { agents } from "./capabilities/agents";
import { commands } from "./capabilities/commands";
import { context } from "./capabilities/context";
import { isProjectLayout, type CodexArtifactKind } from "./capabilities/layout";
import { hooks } from "./capabilities/hooks";
import { mcp } from "./capabilities/mcp";
import { writeCodexPluginManifest, type CodexPluginManifest } from "./capabilities/manifest";
import { skills } from "./capabilities/skills";

export type WriteContext = CoreWriteContext;

const TARGET = "codex";

/**
 * Computes the `ArtifactChange[]` needed to make a Codex project or Plugin
 * directory match `canonical`, without performing I/O itself — Core
 * executes approved changes (per the Adapter/Core split frozen in JUE-103's
 * Extension Host).
 *
 * Plugin mode writes portable `skills/` + `.mcp.json` (RFC-0002 / OpenClaw
 * compatible-bundle). Project mode keeps MCP as an honest TOML no-op.
 */
export async function write(
  canonical: CanonicalDocument,
  writeContext: WriteContext,
): Promise<ArtifactChange[]> {
  const artifactKind = (
    writeContext.artifactKind ?? (isProjectLayout(writeContext.artifactRoot) ? "project" : "project")
  ) as CodexArtifactKind;

  let changes = writeCapabilities(
    {
      commands: commands(),
      agents: agents(),
      skills: skills(artifactKind),
      hooks: hooks(),
      mcp: mcp(artifactKind),
    },
    canonical as unknown as Record<string, unknown>,
    writeContext.artifactRoot,
    TARGET,
  );

  if (artifactKind === "project" && canonical.context?.global) {
    changes.push(...context().write(writeContext.artifactRoot, { global: canonical.context.global }, TARGET));
  }

  if (artifactKind === "plugin") {
    let manifest = writeContext.pluginManifest as CodexPluginManifest | undefined;
    if (!manifest) {
      // Try to read an existing on-disk manifest (a fixture's own).
      const existingManifestPath = path.join(writeContext.artifactRoot, ".codex-plugin", "plugin.json");
      if (fs.existsSync(existingManifestPath)) {
        try {
          manifest = JSON.parse(fs.readFileSync(existingManifestPath, "utf8")) as CodexPluginManifest;
        } catch {
          throw new Error(
            `Codex Plugin manifest at ${existingManifestPath} is not valid JSON; refusing to replace it implicitly.`,
          );
        }
      }
    }
    const candidate = manifest ?? {
      name: "jue-plugin",
      version: "0.1.0",
      description: "Generated by ai-jue",
    };
    if (
      typeof candidate.name !== "string" ||
      !candidate.name.trim() ||
      typeof candidate.version !== "string" ||
      !candidate.version.trim()
    ) {
      throw new Error(
        `Codex Plugin manifest at ${path.join(writeContext.artifactRoot, ".codex-plugin", "plugin.json")} must contain non-empty name and version fields.`,
      );
    }
    manifest = {
      ...candidate,
      name: candidate.name.trim(),
      version: candidate.version.trim(),
      description:
        typeof candidate.description === "string" && candidate.description.trim()
          ? candidate.description.trim()
          : "Generated by ai-jue",
    };
    changes.push(
      ...writeCodexPluginManifest(writeContext.artifactRoot, manifest, TARGET),
    );
  }

  return changes;
}
