import fs from "fs";
import os from "os";
import path from "path";
import { execFileSync } from "child_process";
import { afterEach, describe, expect, it } from "vitest";
import { applyChangesOrThrow } from "ai-jue-core";
import { hasCli } from "../../ai-jue-core/test/has-cli";
import { write } from "../src/write";
import type { CanonicalDocument } from "ai-jue-core";

const hasClaudeCli = hasCli("claude");

const tempDirs: string[] = [];
function tempDir(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "jue-claude-plugin-manifest-"));
  tempDirs.push(dir);
  return dir;
}
afterEach(() => {
  for (const dir of tempDirs.splice(0)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

const CANONICAL: CanonicalDocument = {
  skills: {
    demo: { name: "demo", description: "Neutral fixture skill", content: "Do the thing." },
  },
};

describe("write() with a Plugin manifest", () => {
  it("omits .claude-plugin/plugin.json when no manifest is supplied (manifest-optional Plugin)", async () => {
    const root = tempDir();
    applyChangesOrThrow(root, await write(CANONICAL, { scope: "project", artifactRoot: root, artifactKind: "plugin" }));

    expect(fs.existsSync(path.join(root, ".claude-plugin", "plugin.json"))).toBe(false);
    expect(fs.existsSync(path.join(root, "skills", "demo", "SKILL.md"))).toBe(true);
  });

  it("writes a Plugin manifest when supplied", async () => {
    const root = tempDir();
    const changes = await write(CANONICAL, {
      scope: "project",
      artifactRoot: root,
      artifactKind: "plugin",
      pluginManifest: {
        name: "jue-write-test-plugin",
        version: "1.0.0",
        description: "Neutral fixture Plugin generated by write() for native verification.",
        author: { name: "ai-jue fixtures" },
      },
    });
    applyChangesOrThrow(root, changes);

    const manifestPath = path.join(root, ".claude-plugin", "plugin.json");
    expect(fs.existsSync(manifestPath)).toBe(true);
    expect(JSON.parse(fs.readFileSync(manifestPath, "utf8"))).toMatchObject({
      name: "jue-write-test-plugin",
      version: "1.0.0",
    });
  });

  it.skipIf(!hasClaudeCli)(
    "writes a manifest that passes real `claude plugin validate --strict`",
    async () => {
      const root = tempDir();
      const changes = await write(CANONICAL, {
        scope: "project",
        artifactRoot: root,
        artifactKind: "plugin",
        pluginManifest: {
          name: "jue-write-test-plugin",
          version: "1.0.0",
          description: "Neutral fixture Plugin generated by write() for native verification.",
          author: { name: "ai-jue fixtures" },
        },
      });
      applyChangesOrThrow(root, changes);

      const result = execFileSync("claude", ["plugin", "validate", root, "--strict"], {
        encoding: "utf8",
      });
      expect(result).toContain("Validation passed");
    },
    30_000,
  );
});
