import { Arguments, CommandBuilder } from "yargs";
import path from "path";
import fs from "fs";
import { logger } from "../logger";
import { t } from "../i18n";

export const command = "create-preset <name>";
export const describe = "";

export const builder: CommandBuilder = (yargs) => {
  return yargs.positional("name", {
    describe: t("commands.create-preset.ask_name"),
    type: "string",
    demandOption: true,
  });
};

export const handler = async (argv: Arguments) => {
  const name = argv.name as string;
  const packageName = `jue-preset-${name}`;
  const targetDir = path.join(process.cwd(), packageName);

  if (fs.existsSync(targetDir)) {
    logger.error(t("commands.init.already_exists")); // Reusing for directory exists
    process.exitCode = 1;
    return;
  }

  logger.info(t("commands.create-preset.running", { name: packageName }));
  fs.mkdirSync(targetDir);
  fs.mkdirSync(path.join(targetDir, "prompts"));
  fs.mkdirSync(path.join(targetDir, "skills"));

  // Create sample skill
  const sampleSkillDir = path.join(targetDir, "skills", "example-skill");
  fs.mkdirSync(sampleSkillDir);
  fs.writeFileSync(
    path.join(sampleSkillDir, "prompt.md"),
    "This is an example skill prompt.",
  );
  fs.writeFileSync(
    path.join(sampleSkillDir, "META.json"),
    JSON.stringify(
      {
        description: "An example skill generated by create-preset",
      },
      null,
      2,
    ),
  );

  const packageJson = {
    name: packageName,
    version: "1.0.0",
    description: `AI-Jue preset for ${name}`,
    main: "index.js",
    keywords: ["jue-preset"],
    license: "MIT",
  };

  fs.writeFileSync(
    path.join(targetDir, "package.json"),
    JSON.stringify(packageJson, null, 2),
  );
  fs.writeFileSync(
    path.join(targetDir, "README.md"),
    `# ${packageName}\n\nAI-Jue preset for ${name}.`,
  );

  logger.success(
    t("commands.create-preset.success", { name: packageName, path: targetDir }),
  );
  // Next steps text remains same for now as it contains code commands
  logger.info(
    `\nNext steps:\n  cd ${packageName}\n  npm install\n  # Add your prompts and skills in prompts/ and skills/ directories`,
  );
};
