import { Arguments, CommandBuilder } from 'yargs';
import path from 'path';
import fs from 'fs';
import { logger } from '../logger';

export const command = 'create-preset <name>';
export const describe = 'Create a new preset project';

export const builder: CommandBuilder = (yargs) => {
    return yargs.positional('name', {
        describe: 'Name of the preset (without jue-preset- prefix)',
        type: 'string',
        demandOption: true
    });
};

export const handler = async (argv: Arguments) => {
    const name = argv.name as string;
    const packageName = `jue-preset-${name}`;
    const targetDir = path.join(process.cwd(), packageName);
    
    if (fs.existsSync(targetDir)) {
        logger.error(`Directory ${packageName} already exists.`);
        process.exitCode = 1;
        return;
    }
    
    logger.info(`Creating preset project in ${targetDir}...`);
    fs.mkdirSync(targetDir);
    fs.mkdirSync(path.join(targetDir, 'prompts'));
    fs.mkdirSync(path.join(targetDir, 'skills'));
    
    // Create sample skill
    const sampleSkillDir = path.join(targetDir, 'skills', 'example-skill');
    fs.mkdirSync(sampleSkillDir);
    fs.writeFileSync(path.join(sampleSkillDir, 'prompt.md'), 'This is an example skill prompt.');
    fs.writeFileSync(path.join(sampleSkillDir, 'META.json'), JSON.stringify({
        description: 'An example skill generated by create-preset'
    }, null, 2));

    const packageJson = {
        name: packageName,
        version: '1.0.0',
        description: `AI-Jue preset for ${name}`,
        main: 'index.js',
        keywords: ['jue-preset'],
        license: 'MIT'
    };
    
    fs.writeFileSync(path.join(targetDir, 'package.json'), JSON.stringify(packageJson, null, 2));
    fs.writeFileSync(path.join(targetDir, 'README.md'), `# ${packageName}\n\nAI-Jue preset for ${name}.`);
    
    logger.success(`Preset ${packageName} created successfully!`);
    logger.info(`\nNext steps:\n  cd ${packageName}\n  npm install\n  # Add your prompts and skills in prompts/ and skills/ directories`);
};
