import fs from "fs";
import path from "path";

/**
 * Hermes Artifact kinds (RFC-0002):
 * - `workspace`: MEMORY.md / skills/<cat>/<name> / config.yaml / cron — JUE-303
 * - `skill-plugin`: thin plugin.yaml + register_skill initializer + flat skills
 */
export type HermesArtifactKind = "workspace" | "skill-plugin";

export function isWorkspaceLayout(root: string): boolean {
  return (
    fs.existsSync(path.join(root, "config.yaml")) ||
    fs.existsSync(path.join(root, "skills")) ||
    fs.existsSync(path.join(root, "cron")) ||
    fs.existsSync(path.join(root, "MEMORY.md"))
  );
}

/**
 * Generated skill-plugin marker: the `__init__.py` we write is a fixed
 * template whose docstring carries this fingerprint. A plain Python package
 * (`__init__.py` is a near-universal file) with a coincidental
 * `plugin.yaml` must never be claimed as managed.
 */
export const MANAGED_INIT_MARKER = "Auto-generated by ai-jue";
export const MANAGED_INIT_SOURCE = `"""Auto-generated by ai-jue — registers bundled skills only (no tools)."""
from pathlib import Path


def register(ctx):
    skills_dir = Path(__file__).parent / "skills"
    if not skills_dir.is_dir():
        return
    for child in sorted(skills_dir.iterdir()):
        skill_md = child / "SKILL.md"
        if child.is_dir() and skill_md.is_file():
            ctx.register_skill(child.name, skill_md)
`;

/** Return a managed layout only when its initializer bytes are exactly ours. */
export function detectArtifactKind(root: string): HermesArtifactKind | undefined {
  const initPath = path.join(root, "__init__.py");
  if (
    fs.existsSync(path.join(root, "plugin.yaml")) &&
    fs.existsSync(initPath) &&
    fs.readFileSync(initPath, "utf8") === MANAGED_INIT_SOURCE
  ) {
    return "skill-plugin";
  }
  if (isWorkspaceLayout(root)) return "workspace";
  return undefined;
}
