import fs from "fs";
import path from "path";

/**
 * Hermes Artifact kinds (RFC-0002):
 * - `workspace`: MEMORY.md / skills/<cat>/<name> / config.yaml / cron — JUE-303
 * - `skill-plugin`: thin plugin.yaml + register_skill initializer + flat skills
 */
export type HermesArtifactKind = "workspace" | "skill-plugin";

export function isWorkspaceLayout(root: string): boolean {
  return (
    fs.existsSync(path.join(root, "config.yaml")) ||
    fs.existsSync(path.join(root, "skills")) ||
    fs.existsSync(path.join(root, "cron")) ||
    fs.existsSync(path.join(root, "MEMORY.md"))
  );
}

/**
 * Generated skill-plugin marker: the `__init__.py` we write is a fixed
 * template whose docstring carries this fingerprint. A plain Python package
 * (`__init__.py` is a near-universal file) with a coincidental
 * `plugin.yaml` must never be claimed as managed.
 */
export const MANAGED_INIT_MARKER = "Auto-generated by ai-jue";

/** Return a managed layout only when its marker is present. */
export function detectArtifactKind(root: string): HermesArtifactKind | undefined {
  const initPath = path.join(root, "__init__.py");
  if (
    fs.existsSync(path.join(root, "plugin.yaml")) &&
    fs.existsSync(initPath) &&
    fs.readFileSync(initPath, "utf8").includes(MANAGED_INIT_MARKER)
  ) {
    return "skill-plugin";
  }
  if (isWorkspaceLayout(root)) return "workspace";
  return undefined;
}
