import fs from "fs";
import path from "path";
import * as yaml from "js-yaml";
import { directoryPerItem, hashArtifactContent } from "ai-jue-core";
import type { ArtifactChange, CanonicalDocument } from "ai-jue-core";
import { MANAGED_INIT_MARKER } from "./layout";

const TARGET = "hermes";
const SAFE_SKILL_NAME = /^[A-Za-z0-9][A-Za-z0-9._-]*$/;

function assertSafeSkillName(name: string): void {
  if (!SAFE_SKILL_NAME.test(name)) {
    throw new Error(`Hermes skill-plugin name must be a safe single path segment: ${name}`);
  }
}

const INIT_PY = `"""Auto-generated by ai-jue — registers bundled skills only (no tools)."""
from pathlib import Path


def register(ctx):
    skills_dir = Path(__file__).parent / "skills"
    if not skills_dir.is_dir():
        return
    for child in sorted(skills_dir.iterdir()):
        skill_md = child / "SKILL.md"
        if child.is_dir() and skill_md.is_file():
            ctx.register_skill(child.name, skill_md)
`;

function textChange(
  root: string,
  absolutePath: string,
  newContent: string,
): ArtifactChange | null {
  const exists = fs.existsSync(absolutePath);
  const existing = exists ? fs.readFileSync(absolutePath, "utf8") : undefined;
  if (existing === newContent) return null;
  return {
    target: TARGET,
    kind: exists ? "update" : "create",
    ownership: "full",
    scope: "project",
    path: path.relative(root, absolutePath).split(path.sep).join("/"),
    beforeHash: exists ? hashArtifactContent(existing as string) : null,
    afterHash: hashArtifactContent(newContent),
    content: newContent,
    risk: "low",
    requiresApproval: false,
    atomicState: "planned",
  };
}

/**
 * Thin Hermes skill-plugin (RFC-0002 Phase B):
 *   plugin.yaml + __init__.py (register_skill only) + flat skills/<name>/
 *
 * MCP / context stay on workspace apply — not packed here.
 */
export function writeSkillPlugin(
  canonical: CanonicalDocument,
  root: string,
  pluginManifest?: { name: string; version: string; description?: string },
): ArtifactChange[] {
  const changes: ArtifactChange[] = [];
  // `__init__.py` is user Python code; only ever touch it when it is ours.
  // Refuse (fail explicit) rather than overwrite a hand-authored package.
  const initPath = path.join(root, "__init__.py");
  if (
    fs.existsSync(initPath) &&
    !fs.readFileSync(initPath, "utf8").includes(MANAGED_INIT_MARKER)
  ) {
    throw new Error(
      "Hermes skill-plugin refuses to overwrite a hand-authored __init__.py; " +
        "remove it or point the plugin at an empty directory.",
    );
  }
  const name = pluginManifest?.name?.trim() || "jue-skills";
  const version = pluginManifest?.version?.trim() || "0.1.0";
  const description =
    pluginManifest?.description?.trim() ||
    "Skill pack generated by ai-jue from Canonical skills.";

  const manifestYaml = yaml.dump(
    { name, version, description },
    { lineWidth: -1, noRefs: true },
  );
  const manifestChange = textChange(root, path.join(root, "plugin.yaml"), manifestYaml);
  if (manifestChange) changes.push(manifestChange);

  const initChange = textChange(root, path.join(root, "__init__.py"), INIT_PY);
  if (initChange) changes.push(initChange);

  if (canonical.skills && Object.keys(canonical.skills).length > 0) {
    // Flatten "<category>/<name>" keys to a single path segment for plugin layout.
    const flatSkills: Record<string, unknown> = Object.create(null);
    const seenNames = new Set<string>();
    for (const [key, skill] of Object.entries(canonical.skills)) {
      const base = key.includes("/") ? key.split("/").pop()! : key;
      assertSafeSkillName(base);
      if (seenNames.has(base)) {
        throw new Error(
          `Hermes skill-plugin cannot flatten multiple Canonical skills to "${base}"; ` +
            `rename the colliding category/name entries before writing.`,
        );
      }
      seenNames.add(base);
      flatSkills[base] = skill;
    }
    const mapping = directoryPerItem({
      dirPath: (r) => path.join(r, "skills"),
      mainFileName: "SKILL.md",
      // Preserve ai-assets sidecars; Hermes loads SKILL.md and can follow relative refs.
      bundleKeys: ["references", "scripts", "assets"],
    });
    changes.push(...mapping.write(root, flatSkills, TARGET));
  }

  return changes;
}
